services:
  database:
    image: mariadb
    container_name: learnhub_database
    environment:
      MARIADB_DATABASE: learnhub
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3315:3306"
    volumes:
      - database_data:/var/lib/mysql

volumes:
  database_data:
